name: CI de Verificação

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o código (Oficial - sabemos que funciona)
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configurar o Node.js (Oficial)
      # Precisamos disso para instalar o validador
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versão 20 do Node

      # 3. Instalar o validador de HTML
      # 'npm' é o gerenciador de pacotes que vem com o Node
      - name: Instalar o html-validate
        run: npm install html-validate

      # 4. Rodar o validador no seu arquivo
      # 'npx' é o comando para rodar o pacote que acabamos de instalar
      - name: Validar HTML
        run: npx html-validate web/index.html